name: Internal Release

on:
  push:
    branches:
      - release/**

jobs:
  release:
    name: Validate and release
    runs-on: ubuntu-latest
    env:
      SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
      SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
      SIGNING_STORE_FILE: ${{ secrets.SIGNING_STORE_FILE }}
      SIGNING_STORE_PASSWORD: ${{ secrets.SIGNING_STORE_PASSWORD }}
      GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON }}
      KEYSTORE: ${{ secrets.KEYSTORE }}
      VERSION_CODE: ${{ secrets.VERSION_CODE }}
    steps:
      - uses: actions/checkout@v2
      - name: Add secrets
        run: |
          echo "signing.key.alias=$SIGNING_KEY_ALIAS" >> local.properties
          echo "signing.key.password=$SIGNING_KEY_PASSWORD" >> local.properties
          echo "signing.store.file=$SIGNING_STORE_FILE" >> local.properties
          echo "signing.store.password=$SIGNING_STORE_PASSWORD" >> local.properties
          echo $GOOGLE_SERVICES_JSON | base64 -di > app/google-services.json
          echo $KEYSTORE | base64 -di > app/keystore.jks
      - name: Unit tests
        run: bash ./gradlew testDevDebugUnitTest
      - name: Update release version
        id: version
        run: |
          version_name="\"${GITHUB_REF##*/}\""
          sed -i "s/BuildAndroidConfig.VERSION_NAME/$version_name/g" app/build.gradle.kts
          sed -i "s/BuildAndroidConfig.VERSION_CODE/$VERSION_CODE/g" app/build.gradle.kts
          echo "::set-output name=version_name::$version_name"
      - name: Build Signed Bundle
        run: bash ./gradlew :app:bundleProdRelease
      - name: Upload Bundle artifact
        uses: actions/upload-artifact@v1
        with:
          name: app-release
          path: app/build/outputs/bundle/prodRelease/app-prod-release.aab
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.version.outputs.version_name }}
          release_name: Version ${{ steps.version.outputs.version_name }}
          body: |
            Changes in this Release
            - First Change
            - Second Change
          draft: false
          prerelease: true
      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: app/build/outputs/bundle/prodRelease/app-prod-release.aab
          asset_name: englishisfun.aab
          asset_content_type: application/zip

  uploadBundle:
    name: Upload Bundle to Google Play
    runs-on: ubuntu-latest
    needs: release
    steps:
      - uses: actions/checkout@v2
      - name: Download app Bundle
        uses: actions/download-artifact@v1
        with:
          name: app-release
      - name: Upload Android Release to Play Store
        uses: r0adkll/upload-google-play@v1.0.4
        with:
          serviceAccountJsonPlainText: ${{ secrets.SERVICE_ACCOUNT }}
          packageName: com.jpaya.englishisfun
          releaseFile: app-release/app-prod-release.aab
          track: internal
          whatsNewDirectory: whatsnew
