name: UI Tests

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  run:
    runs-on: macos-latest
    continue-on-error: true
    strategy:
      fail-fast: false
    env:
      SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
      SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
      SIGNING_STORE_FILE: ${{ secrets.SIGNING_STORE_FILE }}
      SIGNING_STORE_PASSWORD: ${{ secrets.SIGNING_STORE_PASSWORD }}
      GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Secrets
        run: |
          echo "signing.key.alias=$SIGNING_KEY_ALIAS" >> local.properties
          echo "signing.key.password=$SIGNING_KEY_PASSWORD" >> local.properties
          echo "signing.store.file=$SIGNING_STORE_FILE" >> local.properties
          echo "signing.store.password=$SIGNING_STORE_PASSWORD" >> local.properties
          echo $GOOGLE_SERVICES_JSON | base64 --decode >> app/src/prod/google-services.json

      - name: Run UI tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          arch: x86_64
          script: ./gradlew connectedProdDebugAndroidTest --no-daemon --stacktrace
